---
abstract: 'A plugin for Nephia that provides TOML Response DSL'
author:
  - 'papix <mail@papix.net>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.9.0, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-TOML
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Nephia::Plugin::TOML:
    file: lib/Nephia/Plugin/TOML.pm
    version: 0.80
requires:
  Nephia: 0.80
  TOML: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/nephia/Nephia-Plugin-TOML/issues
  homepage: https://github.com/nephia/Nephia-Plugin-TOML
  repository: git://github.com/nephia/Nephia-Plugin-TOML.git
version: 0.80
